package main

var tags []string = []string{
    //"!DOCTYPE", implemented manually 
    "abbr",
    "address",
    "area",
    "article",
    "aside",
    "audio",
    "b",
    "base",
    "bdi",
    "bdo",
    "blockquote",
    "body",
    "br",
    "button",
    "canvas",
    "caption",
    "cite",
    "code",
    "col",
    "colgroup",
    "command",
    "datalist",
    "dd",
    "del",
    "details",
    "dfn",
    "div",
    "dl",
    "dt",
    "em",
    "embed",
    "fieldset",
    "figcaption",
    "figure",
    "footer",
    "form",
    "h1",
    "h2",
    "h3",
    "h4",
    "h5",
    "h6",
    "head",
    "header",
    "hgroup",
    "hr",
    "html",
    "i",
    "iframe",
    "img",
    "input",
    "ins",
}

var selfClosingTags map[string]struct{} = map[string]struct{}{
    "area":		struct{}{},
    "base":		struct{}{},
    "br":		struct{}{},
    "col":		struct{}{},
    "embed":		struct{}{},
    "hr":		struct{}{},
    "img":		struct{}{},
    "input":		struct{}{},
    "link":		struct{}{},
    "meta":		struct{}{},
    "param":		struct{}{},
    "source":		struct{}{},
    "track":		struct{}{},
    "wbr":		struct{}{},
}
